<?php
if ( ! defined( 'ABSPATH' ) ) exit;
if (! Isset ($wpdb)) $wpdb = $GLOBALS ['wpdb'];
global $wpdb;
ini_set('max_execution_time', 0); 
ini_set('memory_limit','-1');
$table_name   = $wpdb->prefix . "rich_web_video_slider_font_family";
$table_name1  = $wpdb->prefix . "rich_web_video_slider_id";
$table_name2  = $wpdb->prefix . "rich_web_video_slider_manager";
$table_name3  = $wpdb->prefix . "rich_web_video_slider_videos";
$table_name4  = $wpdb->prefix . "rich_web_video_slider_effects_data";
$table_name5  = $wpdb->prefix . "rich_web_vs_effect_1";
$table_name7  = $wpdb->prefix . "rich_web_vs_effect_3";
$table_name8  = $wpdb->prefix . "rich_web_vs_effect_4";
$table_name10 = $wpdb->prefix . "rich_web_vs_effect_6";
$table_name11 = $wpdb->prefix . "rich_web_vs_effect_7";
$table_name12 = $wpdb->prefix . "rich_web_vs_effect_8";
$table_name13 = $wpdb->prefix . "rich_web_vs_effect_9";
$table_name5_Loader = $wpdb->prefix . "rich_web_vs_effect_1_loader";
$table_name7_Loader = $wpdb->prefix . "rich_web_vs_effect_3_loader";
$table_name8_Loader = $wpdb->prefix . "rich_web_vs_effect_4_loader";
$table_name10_Loader = $wpdb->prefix . "rich_web_vs_effect_6_loader";
$table_name11_Loader = $wpdb->prefix . "rich_web_vs_effect_7_loader";
$table_name12_Loader = $wpdb->prefix . "rich_web_vs_effect_8_loader";
$table_name13_Loader = $wpdb->prefix . "rich_web_vs_effect_9_loader";
require_once(ABSPATH . 'wp-admin/includes/upgrade.php');
$sql   = 'CREATE TABLE IF NOT EXISTS ' .$table_name .' ( id INTEGER(10) UNSIGNED AUTO_INCREMENT, Font_family VARCHAR(255) NOT NULL, PRIMARY KEY (id))';
$sql1  = 'CREATE TABLE IF NOT EXISTS ' .$table_name1 . '( id INTEGER(10) UNSIGNED AUTO_INCREMENT, Slider_ID INTEGER(10) NOT NULL, PRIMARY KEY (id))';
$sql2  = 'CREATE TABLE IF NOT EXISTS ' .$table_name2 . '( id INTEGER(10) UNSIGNED AUTO_INCREMENT, Slider_Title VARCHAR(255) NOT NULL, Slider_Type VARCHAR(255) NOT NULL, Slider_Video_Quantity INTEGER(10) NOT NULL, PRIMARY KEY (id))';		
$sql3  = 'CREATE TABLE IF NOT EXISTS ' .$table_name3 . '( id INTEGER(10) UNSIGNED AUTO_INCREMENT, Rich_Web_VSlider_Vid_Title VARCHAR(255) NOT NULL, Rich_Web_VSlider_Add_Desc LONGTEXT NOT NULL, Rich_Web_VSldier_Add_Img VARCHAR(255) NOT NULL, Rich_Web_VSldier_Add_Vid VARCHAR(255) NOT NULL, Rich_Web_VSldier_Add_Src VARCHAR(255) NOT NULL, Rich_Web_VSldier_Add_Link VARCHAR(255) NOT NULL, Rich_Web_VSldier_Add_ONT VARCHAR(255) NOT NULL, Slider_ID INTEGER(10) NOT NULL, PRIMARY KEY (id))';
$sql4  = 'CREATE TABLE IF NOT EXISTS ' .$table_name4 . '( id INTEGER(10) UNSIGNED AUTO_INCREMENT, slider_vid_name VARCHAR(255) NOT NULL, slider_Vid_type VARCHAR(255) NOT NULL, PRIMARY KEY (id))';		
$sql5  = 'CREATE TABLE IF NOT EXISTS ' .$table_name5 . '( id INTEGER(10) UNSIGNED AUTO_INCREMENT, RW_VS_ID VARCHAR(255) NOT NULL, Rich_Web_VSlider_Option_Name VARCHAR(255) NOT NULL, Rich_Web_VSlider_Option_Type VARCHAR(255) NOT NULL, Rich_Web_VS_CP_CE VARCHAR(255) NOT NULL, Rich_Web_VS_CP_EE VARCHAR(255) NOT NULL, Rich_Web_VS_CP_S VARCHAR(255) NOT NULL, Rich_Web_VS_CP_BlC VARCHAR(255) NOT NULL, Rich_Web_VS_CP_BlR VARCHAR(255) NOT NULL, Rich_Web_VS_CP_AS VARCHAR(255) NOT NULL, Rich_Web_VS_CP_PT VARCHAR(255) NOT NULL, Rich_Web_VS_CP_SS VARCHAR(255) NOT NULL, Rich_Web_VS_CS_AP VARCHAR(255) NOT NULL, Rich_Web_VS_CS_HP VARCHAR(255) NOT NULL, Rich_Web_VS_CS_RS VARCHAR(255) NOT NULL, Rich_Web_VS_CS_BSC VARCHAR(255) NOT NULL, Rich_Web_VS_CP_BW VARCHAR(255) NOT NULL, Rich_Web_VS_CP_BS VARCHAR(255) NOT NULL, Rich_Web_VS_CS_BC VARCHAR(255) NOT NULL, Rich_Web_VS_CP_BR VARCHAR(255) NOT NULL, Rich_Web_VS_CS_CN VARCHAR(255) NOT NULL, Rich_Web_VS_CS_NPB VARCHAR(255) NOT NULL, Rich_Web_VS_CP_NO VARCHAR(255) NOT NULL, Rich_Web_VS_CS_NT VARCHAR(255) NOT NULL, Rich_Web_VS_CP_NT VARCHAR(255) NOT NULL, Rich_Web_VS_CP_AT VARCHAR(255) NOT NULL, Rich_Web_VS_CP_CapS VARCHAR(255) NOT NULL, Rich_Web_VS_CP_CapEs VARCHAR(255) NOT NULL, Rich_Web_VS_CP_CapO VARCHAR(255) NOT NULL, Rich_Web_VS_CP_CapE VARCHAR(255) NOT NULL, Rich_Web_VS_CP_TFS VARCHAR(255) NOT NULL, Rich_Web_VS_CP_TFF VARCHAR(255) NOT NULL, Rich_Web_VS_CS_TBgC VARCHAR(255) NOT NULL, Rich_Web_VS_CS_TC VARCHAR(255) NOT NULL, Rich_Web_VS_CP_DFS VARCHAR(255) NOT NULL, Rich_Web_VS_CP_DFF VARCHAR(255) NOT NULL, Rich_Web_VS_CS_DBgC VARCHAR(255) NOT NULL, Rich_Web_VS_CS_DC VARCHAR(255) NOT NULL, Rich_Web_VS_CP_TiT VARCHAR(255) NOT NULL, Rich_Web_VS_CS_TiBgC VARCHAR(255) NOT NULL, Rich_Web_VS_CS_TiC VARCHAR(255) NOT NULL, Rich_Web_VS_CP_TiO VARCHAR(255) NOT NULL, Rich_Web_VS_CP_TiD VARCHAR(255) NOT NULL, Rich_Web_VS_CP_TiP VARCHAR(255) NOT NULL, Rich_Web_VS_CP_TiS VARCHAR(255) NOT NULL, Rich_Web_VS_CP_TiBS VARCHAR(255) NOT NULL, Rich_Web_VS_CP_TiBC VARCHAR(255) NOT NULL, Rich_Web_VS_CP_TiBSt VARCHAR(255) NOT NULL, Rich_Web_VS_CP_TiPos VARCHAR(255) NOT NULL, Rich_Web_VS_SL_Width VARCHAR(255) NOT NULL, Rich_Web_VS_SL_Height VARCHAR(255) NOT NULL, Rich_Web_VS_TitDesc_Type VARCHAR(255) NOT NULL, PRIMARY KEY (id))';
$sql7  = 'CREATE TABLE IF NOT EXISTS ' .$table_name7 . '( id INTEGER(10) UNSIGNED AUTO_INCREMENT, RW_VS_ID VARCHAR(255) NOT NULL, Rich_Web_VSlider_Option_Name VARCHAR(255) NOT NULL, Rich_Web_VSlider_Option_Type VARCHAR(255) NOT NULL, Rich_Web_VS_TS_W VARCHAR(255) NOT NULL, Rich_Web_VS_TS_H VARCHAR(255) NOT NULL, Rich_Web_VS_TS_BW VARCHAR(255) NOT NULL, Rich_Web_VS_TS_BS VARCHAR(255) NOT NULL, Rich_Web_VS_TS_BC VARCHAR(255) NOT NULL, Rich_Web_VS_TS_BoxShShow VARCHAR(255) NOT NULL, Rich_Web_VS_TS_BoxShType VARCHAR(255) NOT NULL, Rich_Web_VS_TS_BoxSh VARCHAR(255) NOT NULL, Rich_Web_VS_TS_BoxShC VARCHAR(255) NOT NULL, Rich_Web_VS_TS_IBgC VARCHAR(255) NOT NULL, Rich_Web_VS_TS_IBW VARCHAR(255) NOT NULL, Rich_Web_VS_TS_IBS VARCHAR(255) NOT NULL, Rich_Web_VS_TS_IBC VARCHAR(255) NOT NULL, Rich_Web_VS_TS_IBR VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TPos VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TBgC VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TBW VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TBS VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TBC VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TIH VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TIPB VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TIBW VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TIBS VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TIBC VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TIBR VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TIBoxShShow VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TIBoxShType VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TIBoxSh VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TIBoxShC VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TICBC VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TICBS VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TICBoxShC VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TIHBC VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TIHBS VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TIHBoxShC VARCHAR(255) NOT NULL, Rich_Web_VS_TS_CS VARCHAR(255) NOT NULL, Rich_Web_VS_TS_PT VARCHAR(255) NOT NULL, Rich_Web_VS_TS_AP VARCHAR(255) NOT NULL, Rich_Web_VS_TS_PIBgC VARCHAR(255) NOT NULL, Rich_Web_VS_TS_PIC VARCHAR(255) NOT NULL, Rich_Web_VS_TS_PIHBgC VARCHAR(255) NOT NULL, Rich_Web_VS_TS_PIHC VARCHAR(255) NOT NULL, PRIMARY KEY (id))';
$sql8  = 'CREATE TABLE IF NOT EXISTS ' .$table_name8 . '( id INTEGER(10) UNSIGNED AUTO_INCREMENT, RW_VS_ID VARCHAR(255) NOT NULL, Rich_Web_VSlider_Option_Name VARCHAR(255) NOT NULL, Rich_Web_VSlider_Option_Type VARCHAR(255) NOT NULL, Rich_Web_VC_Car_Bg_Color VARCHAR(255) NOT NULL, Rich_Web_VC_Car_Border_Width VARCHAR(255) NOT NULL, Rich_Web_VC_Car_Border_Style VARCHAR(255) NOT NULL, Rich_Web_VC_Car_Border_Color VARCHAR(255) NOT NULL, Rich_Web_VC_Car_Box_Shadow VARCHAR(255) NOT NULL, Rich_Web_VC_Car_Shadow_Color VARCHAR(255) NOT NULL, Rich_Web_VC_Car_Count_Imgs VARCHAR(255) NOT NULL, Rich_Web_VC_Car_Imgs_Hover_Type VARCHAR(255) NOT NULL, Rich_Web_VC_Car_PBImgs VARCHAR(255) NOT NULL, Rich_Web_VC_Car_Icons_Type VARCHAR(255) NOT NULL, Rich_Web_VC_Car_Icons_Size VARCHAR(255) NOT NULL, Rich_Web_VC_Overlay_Bg_Color VARCHAR(255) NOT NULL, Rich_Web_VC_Popup_Bg_Color VARCHAR(255) NOT NULL, Rich_Web_VC_Popup_Border_Width VARCHAR(255) NOT NULL, Rich_Web_VC_Popup_Border_Style VARCHAR(255) NOT NULL, Rich_Web_VC_Popup_Border_Color VARCHAR(255) NOT NULL, Rich_Web_VC_Popup_Box_Shadow VARCHAR(255) NOT NULL, Rich_Web_VC_Popup_Shadow_Color VARCHAR(255) NOT NULL, Rich_Web_VC_Title_Font_Size VARCHAR(255) NOT NULL, Rich_Web_VC_Title_Font_Family VARCHAR(255) NOT NULL, Rich_Web_VC_Title_Color VARCHAR(255) NOT NULL, Rich_Web_VC_Title_Text_Align VARCHAR(255) NOT NULL, Rich_Web_VC_Desc_Bg_Color VARCHAR(255) NOT NULL, Rich_Web_VC_Desc_Font_Size VARCHAR(255) NOT NULL, Rich_Web_VC_Desc_Font_Family VARCHAR(255) NOT NULL, Rich_Web_VC_Desc_Color VARCHAR(255) NOT NULL, Rich_Web_VC_Desc_Text_Align VARCHAR(255) NOT NULL, Rich_Web_VC_Link_Font_Size VARCHAR(255) NOT NULL, Rich_Web_VC_Link_Font_Family VARCHAR(255) NOT NULL, Rich_Web_VC_Link_Color VARCHAR(255) NOT NULL, Rich_Web_VC_Link_Bg_Color VARCHAR(255) NOT NULL, Rich_Web_VC_Link_Border_Color VARCHAR(255) NOT NULL, Rich_Web_VC_Link_Border_Width VARCHAR(255) NOT NULL, Rich_Web_VC_Link_Border_Style VARCHAR(255) NOT NULL, Rich_Web_VC_Link_Hov_Bg_Color VARCHAR(255) NOT NULL, Rich_Web_VC_Link_Hov_Color VARCHAR(255) NOT NULL, Rich_Web_VC_Link_Hov_Border_Color VARCHAR(255) NOT NULL, Rich_Web_VC_Popup_Icons_Size VARCHAR(255) NOT NULL, Rich_Web_VC_Popup_Icons_Color VARCHAR(255) NOT NULL, Rich_Web_VC_Popup_Icons_Type VARCHAR(255) NOT NULL, Rich_Web_VC_Link_Text VARCHAR(255) NOT NULL, Rich_Web_VC_Link_Border_Radius VARCHAR(255) NOT NULL, PRIMARY KEY (id))';
$sql10 = 'CREATE TABLE IF NOT EXISTS ' .$table_name10 . '( id INTEGER(10) UNSIGNED AUTO_INCREMENT, RW_VS_ID VARCHAR(255) NOT NULL, Rich_Web_VSlider_Option_Name VARCHAR(255) NOT NULL, Rich_Web_VSlider_Option_Type VARCHAR(255) NOT NULL, Rich_Web_VTVS_AP VARCHAR(255) NOT NULL, Rich_Web_VTVS_APS VARCHAR(255) NOT NULL, Rich_Web_VTVS_APEff VARCHAR(255) NOT NULL, Rich_Web_VTVS_CS VARCHAR(255) NOT NULL, Rich_Web_VTVS_PT VARCHAR(255) NOT NULL, Rich_Web_VTVS_ArrSt VARCHAR(255) NOT NULL, Rich_Web_VTVS_BgC VARCHAR(255) NOT NULL, Rich_Web_VTVS_H VARCHAR(255) NOT NULL, Rich_Web_VTVS_BW VARCHAR(255) NOT NULL, Rich_Web_VTVS_BS VARCHAR(255) NOT NULL, Rich_Web_VTVS_BC VARCHAR(255) NOT NULL, Rich_Web_VTVS_BoxShShow VARCHAR(255) NOT NULL, Rich_Web_VTVS_BoxShType VARCHAR(255) NOT NULL, Rich_Web_VTVS_BoxSh VARCHAR(255) NOT NULL, Rich_Web_VTVS_BoxShC VARCHAR(255) NOT NULL, Rich_Web_VTVS_TShow VARCHAR(255) NOT NULL, Rich_Web_VTVS_TFS VARCHAR(255) NOT NULL, Rich_Web_VTVS_TFF VARCHAR(255) NOT NULL, Rich_Web_VTVS_TC VARCHAR(255) NOT NULL, Rich_Web_VTVS_TBgC VARCHAR(255) NOT NULL, Rich_Web_VTVS_TPos VARCHAR(255) NOT NULL, Rich_Web_VTVS_Th_BW VARCHAR(255) NOT NULL, Rich_Web_VTVS_Th_BS VARCHAR(255) NOT NULL, Rich_Web_VTVS_Th_BC VARCHAR(255) NOT NULL, Rich_Web_VTVS_Th_BR VARCHAR(255) NOT NULL, Rich_Web_VTVS_Th_HBC VARCHAR(255) NOT NULL,	Rich_Web_VTVS_LC VARCHAR(255) NOT NULL, Rich_Web_VTVS_LBgC VARCHAR(255) NOT NULL, Rich_Web_VTVS_LFS VARCHAR(255) NOT NULL, Rich_Web_VTVS_LHC VARCHAR(255) NOT NULL, Rich_Web_VTVS_LHBgC VARCHAR(255) NOT NULL, Rich_Web_VTVS_LPos VARCHAR(255) NOT NULL, Rich_Web_VTVS_LType VARCHAR(255) NOT NULL, Rich_Web_VTVS_PC VARCHAR(255) NOT NULL, Rich_Web_VTVS_PBgC VARCHAR(255) NOT NULL, Rich_Web_VTVS_PFS VARCHAR(255) NOT NULL, Rich_Web_VTVS_PHC VARCHAR(255) NOT NULL, Rich_Web_VTVS_PHBgC VARCHAR(255) NOT NULL, Rich_Web_VTVS_PPos VARCHAR(255) NOT NULL, Rich_Web_VTVS_PType VARCHAR(255) NOT NULL, Rich_Web_VTVS_ArrShow VARCHAR(255) NOT NULL, Rich_Web_VTVS_ArrType VARCHAR(255) NOT NULL, Rich_Web_VTVS_ArrFS VARCHAR(255) NOT NULL, Rich_Web_VTVS_ArrPos VARCHAR(255) NOT NULL, Rich_Web_VTVS_ArrC VARCHAR(255) NOT NULL, PRIMARY KEY (id))';
$sql11 = 'CREATE TABLE IF NOT EXISTS ' .$table_name11 . '( id INTEGER(10) UNSIGNED AUTO_INCREMENT, RW_VS_ID VARCHAR(255) NOT NULL, Rich_Web_VSlider_Option_Name VARCHAR(255) NOT NULL, Rich_Web_VSlider_Option_Type VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Loop VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Cols VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Speed VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_AP VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_EH VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_PB VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Car VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_NP_Show VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_NP_NText VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_NP_PText VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_NP_C VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_NP_BgC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_NP_FS VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_NP_FF VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_NP_BW VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_NP_BS VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_NP_BC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_NP_BR VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_NP_HC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_NP_HBgC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Cols_BgC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Cols_BoxShC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Cols_VSEff VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Cols_StShC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Cols_VHEff VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Cols_HShC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_TC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_TFS VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_TFF VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_DShow VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_DC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_DFS VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_DFF VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_LText VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_LC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_LFS VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_LFF VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_LHC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_PText VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_PBgC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_PC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_PFS VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_PFF VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_PHC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_PHBgC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Pop_OvC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Pop_BW VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Pop_BS VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Pop_BC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Pop_BoxShShow VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Pop_BoxShType VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Pop_BoxSh VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Pop_BoxShC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Pop_CIType VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Pop_CIS VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Pop_CIC VARCHAR(255) NOT NULL, PRIMARY KEY (id))';
$sql12 = 'CREATE TABLE IF NOT EXISTS ' .$table_name12 . '( id INTEGER(10) UNSIGNED AUTO_INCREMENT, RW_VS_ID VARCHAR(255) NOT NULL, Rich_Web_VSlider_Option_Name VARCHAR(255) NOT NULL, Rich_Web_VSlider_Option_Type VARCHAR(255) NOT NULL, Rich_Web_RVVS_Sh VARCHAR(255) NOT NULL, Rich_Web_RVVS_ShT VARCHAR(255) NOT NULL, Rich_Web_RVVS_ShC VARCHAR(255) NOT NULL, Rich_Web_RVVS_NI_BW VARCHAR(255) NOT NULL, Rich_Web_RVVS_NI_BC VARCHAR(255) NOT NULL, Rich_Web_RVVS_NI_BgC VARCHAR(255) NOT NULL, Rich_Web_RVVS_NI_HBgC VARCHAR(255) NOT NULL, Rich_Web_RVVS_NI_HBC VARCHAR(255) NOT NULL, Rich_Web_RVVS_NI_CBgC VARCHAR(255) NOT NULL, Rich_Web_RVVS_NI_CBC VARCHAR(255) NOT NULL, Rich_Web_RVVS_NT_FF VARCHAR(255) NOT NULL, Rich_Web_RVVS_NT_C VARCHAR(255) NOT NULL, Rich_Web_RVVS_ND_FF VARCHAR(255) NOT NULL, Rich_Web_RVVS_ND_C VARCHAR(255) NOT NULL, Rich_Web_RVVS_NImg_BW VARCHAR(255) NOT NULL, Rich_Web_RVVS_NImg_BR VARCHAR(255) NOT NULL, Rich_Web_RVVS_NImg_BSh VARCHAR(255) NOT NULL, Rich_Web_RVVS_NImg_ShC VARCHAR(255) NOT NULL, Rich_Web_RVVS_NImg_ShT VARCHAR(255) NOT NULL, Rich_Web_RVVS_NScroll_BgC VARCHAR(255) NOT NULL, Rich_Web_RVVS_NScroll_HBgC VARCHAR(255) NOT NULL, Rich_Web_RVVS_NScroll_C VARCHAR(255) NOT NULL, Rich_Web_RVVS_IT_FF VARCHAR(255) NOT NULL, Rich_Web_RVVS_IT_C VARCHAR(255) NOT NULL, Rich_Web_RVVS_ID_FF VARCHAR(255) NOT NULL, Rich_Web_RVVS_ID_C VARCHAR(255) NOT NULL, Rich_Web_RVVS_PlIc_FS VARCHAR(255) NOT NULL, Rich_Web_RVVS_PlIc_C VARCHAR(255) NOT NULL, Rich_Web_RVVS_PlIc_BgC VARCHAR(255) NOT NULL, Rich_Web_RVVS_PlIc_HBgC VARCHAR(255) NOT NULL, Rich_Web_RVVS_DelIc_C VARCHAR(255) NOT NULL, Rich_Web_RVVS_DelIc_T VARCHAR(255) NOT NULL, Rich_Web_RVVS_DelIc_FS VARCHAR(255) NOT NULL, Rich_Web_RVVS_DelIc_BgC VARCHAR(255) NOT NULL, Rich_Web_RVVS_DelIc_HBgC VARCHAR(255) NOT NULL, Rich_Web_RVVS_NT_FS VARCHAR(255) NOT NULL, Rich_Web_RVVS_ND_FS VARCHAR(255) NOT NULL, Rich_Web_RVVS_IT_FS VARCHAR(255) NOT NULL, Rich_Web_RVVS_ID_FS VARCHAR(255) NOT NULL, Rich_Web_RVVS_NT_HC VARCHAR(255) NOT NULL, Rich_Web_RVVS_NT_CC VARCHAR(255) NOT NULL, Rich_Web_RVVS_ND_HC VARCHAR(255) NOT NULL, Rich_Web_RVVS_ND_CC VARCHAR(255) NOT NULL, PRIMARY KEY (id))';
$sql13 = 'CREATE TABLE IF NOT EXISTS ' .$table_name13 . '( id INTEGER(10) UNSIGNED AUTO_INCREMENT, RW_VS_ID VARCHAR(255) NOT NULL, Rich_Web_VSlider_Option_Name VARCHAR(255) NOT NULL, Rich_Web_VSlider_Option_Type VARCHAR(255) NOT NULL, Rich_Web_MS_W VARCHAR(255) NOT NULL, Rich_Web_MS_SSh VARCHAR(255) NOT NULL, Rich_Web_MS_SShChT VARCHAR(255) NOT NULL, Rich_Web_MS_BSh VARCHAR(255) NOT NULL, Rich_Web_MS_ShC VARCHAR(255) NOT NULL, Rich_Web_MS_ShT VARCHAR(255) NOT NULL, Rich_Web_MS_BgC VARCHAR(255) NOT NULL, Rich_Web_MS_Type VARCHAR(255) NOT NULL, Rich_Web_MS_Autoplay VARCHAR(255) NOT NULL, Rich_Web_MS_N_BW VARCHAR(255) NOT NULL, Rich_Web_MS_N_BS VARCHAR(255) NOT NULL, Rich_Web_MS_N_BC VARCHAR(255) NOT NULL, Rich_Web_MS_NI_FS VARCHAR(255) NOT NULL, Rich_Web_MS_NI_FF VARCHAR(255) NOT NULL, Rich_Web_MS_NI_C VARCHAR(255) NOT NULL, Rich_Web_MS_NI_HC VARCHAR(255) NOT NULL, Rich_Web_MS_NI_CC VARCHAR(255) NOT NULL, Rich_Web_MS_NIC_C VARCHAR(255) NOT NULL, Rich_Web_MS_Img_BW VARCHAR(255) NOT NULL, Rich_Web_MS_Img_BS VARCHAR(255) NOT NULL, Rich_Web_MS_Img_BC VARCHAR(255) NOT NULL, Rich_Web_MS_Img_BSh VARCHAR(255) NOT NULL, Rich_Web_MS_Img_ShC VARCHAR(255) NOT NULL, Rich_Web_MS_Img_ShT VARCHAR(255) NOT NULL, Rich_Web_MS_T_FS VARCHAR(255) NOT NULL, Rich_Web_MS_T_FF VARCHAR(255) NOT NULL, Rich_Web_MS_T_C VARCHAR(255) NOT NULL, Rich_Web_MS_T_TA VARCHAR(255) NOT NULL, Rich_Web_MS_T_TSh VARCHAR(255) NOT NULL, Rich_Web_MS_T_TShC VARCHAR(255) NOT NULL, Rich_Web_MS_D_FS VARCHAR(255) NOT NULL, Rich_Web_MS_D_FF VARCHAR(255) NOT NULL, Rich_Web_MS_D_C VARCHAR(255) NOT NULL, Rich_Web_MS_D_TA VARCHAR(255) NOT NULL, Rich_Web_MS_D_TSh VARCHAR(255) NOT NULL, Rich_Web_MS_D_TShC VARCHAR(255) NOT NULL, Rich_Web_MS_Ic_T VARCHAR(255) NOT NULL, Rich_Web_MS_Ic_S VARCHAR(255) NOT NULL, Rich_Web_MS_Ic_C VARCHAR(255) NOT NULL, Rich_Web_MS_startAt VARCHAR(255) NOT NULL, Rich_Web_MS_Sl1EfT VARCHAR(255) NOT NULL, Rich_Web_MS_NI_CCC VARCHAR(255) NOT NULL, Rich_Web_MS_PlIc_T VARCHAR(255) NOT NULL, Rich_Web_MS_PlIc_S VARCHAR(255) NOT NULL, Rich_Web_MS_PlIc_BgC VARCHAR(255) NOT NULL, Rich_Web_MS_PlIc_C VARCHAR(255) NOT NULL, Rich_Web_MS_PlIc_HBgC VARCHAR(255) NOT NULL, Rich_Web_MS_PlIc_HC VARCHAR(255) NOT NULL, PRIMARY KEY (id))';
$sql16 ='CREATE TABLE IF NOT EXISTS ' .$table_name5_Loader . '( id INTEGER(10) UNSIGNED AUTO_INCREMENT, RW_VS_ID VARCHAR(255) NOT NULL, Rich_Web_VS_ContSl_L_Show VARCHAR(255) NOT NULL,Rich_Web_VS_ContSl_LT_Show VARCHAR(255) NOT NULL, Rich_Web_VS_ContSl_LT VARCHAR(255) NOT NULL, Rich_Web_VS_ContSl_L_BgC VARCHAR(255) NOT NULL, Rich_Web_VS_ContSl_L_T VARCHAR(255) NOT NULL, Rich_Web_VS_ContSl_LT_T VARCHAR(255) NOT NULL, Rich_Web_VS_ContSl_LT_FS VARCHAR(255) NOT NULL, Rich_Web_VS_ContSl_LT_FF VARCHAR(255) NOT NULL, Rich_Web_VS_ContSl_LT_C VARCHAR(255) NOT NULL, Rich_Web_VS_ContSl_L_T1_C VARCHAR(255) NOT NULL, Rich_Web_VS_ContSl_L_T2_C VARCHAR(255) NOT NULL, Rich_Web_VS_ContSl_L_T3_C VARCHAR(255) NOT NULL, Rich_Web_VS_ContSl_LT_T2_BC VARCHAR(255) NOT NULL, Rich_Web_VS_ContSl_L_C VARCHAR(255) NOT NULL, Rich_Web_VS_ContSl_LT_T2_AnC VARCHAR(255) NOT NULL, Rich_Web_VS_ContSl_LT_T3_BgC VARCHAR(255) NOT NULL, Rich_Web_VS_ContSl_L_S VARCHAR(255) NOT NULL, Rich_Web_VS_ContSl_Loading_Show VARCHAR(255) NOT NULL, PRIMARY KEY (id) )';
$sql18 ='CREATE TABLE IF NOT EXISTS ' .$table_name7_Loader . '( id INTEGER(10) UNSIGNED AUTO_INCREMENT, RW_VS_ID VARCHAR(255) NOT NULL, Rich_Web_ThumbSl_L_Show VARCHAR(255) NOT NULL, Rich_Web_ThumbSl_LT_Show VARCHAR(255) NOT NULL, Rich_Web_ThumbSl_LT VARCHAR(255) NOT NULL, Rich_Web_ThumbSl_L_BgC VARCHAR(255) NOT NULL, Rich_Web_ThumbSl_L_T VARCHAR(255) NOT NULL, Rich_Web_ThumbSl_LT_T VARCHAR(255) NOT NULL, Rich_Web_ThumbSl_LT_FS VARCHAR(255) NOT NULL, Rich_Web_ThumbSl_LT_FF VARCHAR(255) NOT NULL, Rich_Web_ThumbSl_LT_C VARCHAR(255) NOT NULL, Rich_Web_ThumbSl_L_T1_C VARCHAR(255) NOT NULL, Rich_Web_ThumbSl_L_T2_C VARCHAR(255) NOT NULL, Rich_Web_ThumbSl_L_T3_C VARCHAR(255) NOT NULL, Rich_Web_ThumbSl_LT_T2_BC VARCHAR(255) NOT NULL, Rich_Web_ThumbSl_L_C VARCHAR(255) NOT NULL, Rich_Web_ThumbSl_LT_T2_AnC VARCHAR(255) NOT NULL, Rich_Web_ThumbSl_LT_T3_BgC VARCHAR(255) NOT NULL, Rich_Web_ThumbSl_L_S VARCHAR(255) NOT NULL, Rich_Web_ThumbSl_Loading_Show VARCHAR(255) NOT NULL, PRIMARY KEY (id) )';
$sql19 ='CREATE TABLE IF NOT EXISTS ' .$table_name8_Loader . '( id INTEGER(10) UNSIGNED AUTO_INCREMENT, RW_VS_ID VARCHAR(255) NOT NULL, Rich_Web_VCCP_L_Show VARCHAR(255) NOT NULL, Rich_Web_VCCP_LT_Show VARCHAR(255) NOT NULL, Rich_Web_VCCP_LT VARCHAR(255) NOT NULL, Rich_Web_VCCP_L_BgC VARCHAR(255) NOT NULL, Rich_Web_VCCP_L_T VARCHAR(255) NOT NULL, Rich_Web_VCCP_LT_T VARCHAR(255) NOT NULL, Rich_Web_VCCP_LT_FS VARCHAR(255) NOT NULL, Rich_Web_VCCP_LT_FF VARCHAR(255) NOT NULL, Rich_Web_VCCP_LT_C VARCHAR(255) NOT NULL, Rich_Web_VCCP_L_T1_C VARCHAR(255) NOT NULL, Rich_Web_VCCP_L_T2_C VARCHAR(255) NOT NULL, Rich_Web_VCCP_L_T3_C VARCHAR(255) NOT NULL, Rich_Web_VCCP_LT_T2_BC VARCHAR(255) NOT NULL, Rich_Web_VCCP_L_C VARCHAR(255) NOT NULL, Rich_Web_VCCP_LT_T2_AnC VARCHAR(255) NOT NULL, Rich_Web_VCCP_LT_T3_BgC VARCHAR(255) NOT NULL, Rich_Web_VCCP_L_S VARCHAR(255) NOT NULL, Rich_Web_VCCP_Loading_Show VARCHAR(255) NOT NULL, PRIMARY KEY (id) )';
$sql21 ='CREATE TABLE IF NOT EXISTS ' .$table_name10_Loader . '( id INTEGER(10) UNSIGNED AUTO_INCREMENT, RW_VS_ID VARCHAR(255) NOT NULL, Rich_Web_VSVT_L_Show VARCHAR(255) NOT NULL, Rich_Web_VSVT_LT_Show VARCHAR(255) NOT NULL, Rich_Web_VSVT_LT VARCHAR(255) NOT NULL, Rich_Web_VSVT_L_BgC VARCHAR(255) NOT NULL, Rich_Web_VSVT_L_T VARCHAR(255) NOT NULL, Rich_Web_VSVT_LT_T VARCHAR(255) NOT NULL, Rich_Web_VSVT_LT_FS VARCHAR(255) NOT NULL, Rich_Web_VSVT_LT_FF VARCHAR(255) NOT NULL, Rich_Web_VSVT_LT_C VARCHAR(255) NOT NULL, Rich_Web_VSVT_L_T1_C VARCHAR(255) NOT NULL, Rich_Web_VSVT_L_T2_C VARCHAR(255) NOT NULL, Rich_Web_VSVT_L_T3_C VARCHAR(255) NOT NULL, Rich_Web_VSVT_LT_T2_BC VARCHAR(255) NOT NULL, Rich_Web_VSVT_L_C VARCHAR(255) NOT NULL, Rich_Web_VSVT_LT_T2_AnC VARCHAR(255) NOT NULL, Rich_Web_VSVT_LT_T3_BgC VARCHAR(255) NOT NULL, Rich_Web_VSVT_L_S VARCHAR(255) NOT NULL, Rich_Web_VSVT_Loading_Show VARCHAR(255) NOT NULL, PRIMARY KEY (id) )';
$sql22 ='CREATE TABLE IF NOT EXISTS ' .$table_name11_Loader . '( id INTEGER(10) UNSIGNED AUTO_INCREMENT, RW_VS_ID VARCHAR(255) NOT NULL, Rich_Web_HSL_L_Show VARCHAR(255) NOT NULL, Rich_Web_HSL_LT_Show VARCHAR(255) NOT NULL, Rich_Web_HSL_LT VARCHAR(255) NOT NULL, Rich_Web_HSL_L_BgC VARCHAR(255) NOT NULL, Rich_Web_HSL_L_T VARCHAR(255) NOT NULL, Rich_Web_HSL_LT_T VARCHAR(255) NOT NULL, Rich_Web_HSL_LT_FS VARCHAR(255) NOT NULL, Rich_Web_HSL_LT_FF VARCHAR(255) NOT NULL, Rich_Web_HSL_LT_C VARCHAR(255) NOT NULL, Rich_Web_HSL_L_T1_C VARCHAR(255) NOT NULL, Rich_Web_HSL_L_T2_C VARCHAR(255) NOT NULL, Rich_Web_HSL_L_T3_C VARCHAR(255) NOT NULL, Rich_Web_HSL_LT_T2_BC VARCHAR(255) NOT NULL, Rich_Web_HSL_L_C VARCHAR(255) NOT NULL, Rich_Web_HSL_LT_T2_AnC VARCHAR(255) NOT NULL, Rich_Web_HSL_LT_T3_BgC VARCHAR(255) NOT NULL, Rich_Web_HSL_L_S VARCHAR(255) NOT NULL, Rich_Web_HSL_Loading_Show VARCHAR(255) NOT NULL, PRIMARY KEY (id) )';
$sql23 ='CREATE TABLE IF NOT EXISTS ' .$table_name12_Loader . '( id INTEGER(10) UNSIGNED AUTO_INCREMENT, RW_VS_ID VARCHAR(255) NOT NULL, Rich_Web_RichSl_L_Show VARCHAR(255) NOT NULL, Rich_Web_RichSl_LT_Show VARCHAR(255) NOT NULL, Rich_Web_RichSl_LT VARCHAR(255) NOT NULL, Rich_Web_RichSl_L_BgC VARCHAR(255) NOT NULL, Rich_Web_RichSl_L_T VARCHAR(255) NOT NULL, Rich_Web_RichSl_LT_T VARCHAR(255) NOT NULL, Rich_Web_RichSl_LT_FS VARCHAR(255) NOT NULL, Rich_Web_RichSl_LT_FF VARCHAR(255) NOT NULL, Rich_Web_RichSl_LT_C VARCHAR(255) NOT NULL, Rich_Web_RichSl_L_T1_C VARCHAR(255) NOT NULL, Rich_Web_RichSl_L_T2_C VARCHAR(255) NOT NULL, Rich_Web_RichSl_L_T3_C VARCHAR(255) NOT NULL, Rich_Web_RichSl_LT_T2_BC VARCHAR(255) NOT NULL, Rich_Web_RichSl_L_C VARCHAR(255) NOT NULL, Rich_Web_RichSl_LT_T2_AnC VARCHAR(255) NOT NULL, Rich_Web_RichSl_LT_T3_BgC VARCHAR(255) NOT NULL, Rich_Web_RichSl_L_S VARCHAR(255) NOT NULL, Rich_Web_RichSl_Loading_Show VARCHAR(255) NOT NULL, PRIMARY KEY (id) )';
$sql24 ='CREATE TABLE IF NOT EXISTS ' .$table_name13_Loader . '( id INTEGER(10) UNSIGNED AUTO_INCREMENT, RW_VS_ID VARCHAR(255) NOT NULL, Rich_Web_TSL_L_Show VARCHAR(255) NOT NULL, Rich_Web_TSL_LT_Show VARCHAR(255) NOT NULL, Rich_Web_TSL_LT VARCHAR(255) NOT NULL, Rich_Web_TSL_L_BgC VARCHAR(255) NOT NULL, Rich_Web_TSL_L_T VARCHAR(255) NOT NULL, Rich_Web_TSL_LT_T VARCHAR(255) NOT NULL, Rich_Web_TSL_LT_FS VARCHAR(255) NOT NULL, Rich_Web_TSL_LT_FF VARCHAR(255) NOT NULL, Rich_Web_TSL_LT_C VARCHAR(255) NOT NULL, Rich_Web_TSL_L_T1_C VARCHAR(255) NOT NULL, Rich_Web_TSL_L_T2_C VARCHAR(255) NOT NULL, Rich_Web_TSL_L_T3_C VARCHAR(255) NOT NULL, Rich_Web_TSL_LT_T2_BC VARCHAR(255) NOT NULL, Rich_Web_TSL_L_C VARCHAR(255) NOT NULL, Rich_Web_TSL_LT_T2_AnC VARCHAR(255) NOT NULL, Rich_Web_TSL_LT_T3_BgC VARCHAR(255) NOT NULL, Rich_Web_TSL_L_S VARCHAR(255) NOT NULL, Rich_Web_TSL_Loading_Show VARCHAR(255) NOT NULL, PRIMARY KEY (id) )';
dbDelta($sql);dbDelta($sql1);dbDelta($sql2);dbDelta($sql3);dbDelta($sql4);dbDelta($sql5);dbDelta($sql7);dbDelta($sql8);dbDelta($sql10);dbDelta($sql11);dbDelta($sql12);dbDelta($sql13);dbDelta($sql16);dbDelta($sql18);dbDelta($sql19);dbDelta($sql21);dbDelta($sql22);dbDelta($sql23);dbDelta($sql24);
$sqla   = 'ALTER TABLE ' . $table_name . ' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci';
$sqla1  = 'ALTER TABLE ' . $table_name1 . ' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci';
$sqla2  = 'ALTER TABLE ' . $table_name2 . ' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci';
$sqla3  = 'ALTER TABLE ' . $table_name3 . ' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci';
$sqla4  = 'ALTER TABLE ' . $table_name4 . ' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci';
$sqla5  = 'ALTER TABLE ' . $table_name5 . ' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci';
$sqla7  = 'ALTER TABLE ' . $table_name7 . ' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci';
$sqla8  = 'ALTER TABLE ' . $table_name8 . ' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci';
$sqla10 = 'ALTER TABLE ' . $table_name10 . ' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci';
$sqla11 = 'ALTER TABLE ' . $table_name11 . ' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci';
$sqla12 = 'ALTER TABLE ' . $table_name12 . ' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci';
$sqla13 = 'ALTER TABLE ' . $table_name13 . ' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci';
$sqla16 = 'ALTER TABLE ' . $table_name5_Loader . ' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci';
$sqla18 = 'ALTER TABLE ' . $table_name7_Loader . ' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci';
$sqla19 = 'ALTER TABLE ' . $table_name8_Loader . ' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci';
$sqla21 = 'ALTER TABLE ' . $table_name10_Loader . ' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci';
$sqla22 = 'ALTER TABLE ' . $table_name11_Loader . ' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci';
$sqla23 = 'ALTER TABLE ' . $table_name12_Loader . ' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci';
$sqla24 = 'ALTER TABLE ' . $table_name13_Loader . ' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci';
$wpdb->query($sqla);$wpdb->query($sqla1);$wpdb->query($sqla2);$wpdb->query($sqla3);$wpdb->query($sqla4);$wpdb->query($sqla5);$wpdb->query($sqla7);$wpdb->query($sqla8);$wpdb->query($sqla10);$wpdb->query($sqla11);$wpdb->query($sqla12);$wpdb->query($sqla13);$wpdb->query($sqla16);$wpdb->query($sqla18);$wpdb->query($sqla19);$wpdb->query($sqla21);$wpdb->query($sqla22);$wpdb->query($sqla23);$wpdb->query($sqla24);
$Rich_Web_Fonts = array('Abadi MT Condensed Light','Aharoni','Aldhabi','Andalus','Angsana New','AngsanaUPC','Aparajita','Arabic Typesetting','Arial','Arial Black', 'Batang','BatangChe','Browallia New','BrowalliaUPC','Calibri','Calibri Light','Calisto MT','Cambria','Candara','Century Gothic','Comic Sans MS','Consolas', 'Constantia','Copperplate Gothic','Copperplate Gothic Light','Corbel','Cordia New','CordiaUPC','Courier New','DaunPenh','David','DFKai-SB','DilleniaUPC', 'DokChampa','Dotum','DotumChe','Ebrima','Estrangelo Edessa','EucrosiaUPC','Euphemia','FangSong','Franklin Gothic Medium','FrankRuehl','FreesiaUPC','Gabriola', 'Gadugi','Gautami','Georgia','Gisha','Gulim','GulimChe','Gungsuh','GungsuhChe','Impact','IrisUPC','Iskoola Pota','JasmineUPC','KaiTi','Kalinga','Kartika', 'Khmer UI','KodchiangUPC','Kokila','Lao UI','Latha','Leelawadee','Levenim MT','LilyUPC','Lucida Console','Lucida Handwriting Italic','Lucida Sans Unicode', 'Malgun Gothic','Mangal','Manny ITC','Marlett','Meiryo','Meiryo UI','Microsoft Himalaya','Microsoft JhengHei','Microsoft JhengHei UI','Microsoft New Tai Lue', 'Microsoft PhagsPa','Microsoft Sans Serif','Microsoft Tai Le','Microsoft Uighur','Microsoft YaHei','Microsoft YaHei UI','Microsoft Yi Baiti','MingLiU_HKSCS', 'MingLiU_HKSCS-ExtB','Miriam','Mongolian Baiti','MoolBoran','MS UI Gothic','MV Boli','Myanmar Text','Narkisim','Nirmala UI','News Gothic MT','NSimSun','Nyala', 'Palatino Linotype','Plantagenet Cherokee','Raavi','Rod','Sakkal Majalla','Segoe Print','Segoe Script','Segoe UI Symbol','Shonar Bangla','Shruti','SimHei','SimKai', 'Simplified Arabic','SimSun','SimSun-ExtB','Sylfaen','Tahoma','Times New Roman','Traditional Arabic','Trebuchet MS','Tunga','Utsaah','Vani','Vijaya');
$Rich_WebFontCount=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name WHERE id>%d",0));
if(count($Rich_WebFontCount)==0)
{
	foreach ($Rich_Web_Fonts as $JFonts)
	{
		$wpdb->query($wpdb->prepare("INSERT INTO $table_name (id, Font_family) VALUES (%d, %s)", '', $JFonts));
	}
}
$Rich_Web_VS1=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name5 WHERE id>%d",0));
if(count($Rich_Web_VS1)==0)
{
	$wpdb->query($wpdb->prepare("INSERT INTO $table_name4 (id, slider_vid_name, slider_Vid_type) VALUES (%d, %s, %s)", '', 'Content Slider', 'Content Slider'));
	$Rich_Web_VS_ID=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name4 WHERE slider_vid_name=%s", 'Content Slider'));
	$wpdb->query($wpdb->prepare("INSERT INTO $table_name5 (id, RW_VS_ID, Rich_Web_VSlider_Option_Name, Rich_Web_VSlider_Option_Type, Rich_Web_VS_CP_CE, Rich_Web_VS_CP_EE, Rich_Web_VS_CP_S, Rich_Web_VS_CP_BlC, Rich_Web_VS_CP_BlR, Rich_Web_VS_CP_AS, Rich_Web_VS_CP_PT, Rich_Web_VS_CP_SS, Rich_Web_VS_CS_AP, Rich_Web_VS_CS_HP, Rich_Web_VS_CS_RS, Rich_Web_VS_CS_BSC, Rich_Web_VS_CP_BW, Rich_Web_VS_CP_BS, Rich_Web_VS_CS_BC, Rich_Web_VS_CP_BR, Rich_Web_VS_CS_CN, Rich_Web_VS_CS_NPB, Rich_Web_VS_CP_NO, Rich_Web_VS_CS_NT, Rich_Web_VS_CP_NT, Rich_Web_VS_CP_AT, Rich_Web_VS_CP_CapS, Rich_Web_VS_CP_CapEs, Rich_Web_VS_CP_CapO, Rich_Web_VS_CP_CapE, Rich_Web_VS_CP_TFS, Rich_Web_VS_CP_TFF, Rich_Web_VS_CS_TBgC, Rich_Web_VS_CS_TC, Rich_Web_VS_CP_DFS, Rich_Web_VS_CP_DFF, Rich_Web_VS_CS_DBgC, Rich_Web_VS_CS_DC, Rich_Web_VS_CP_TiT, Rich_Web_VS_CS_TiBgC, Rich_Web_VS_CS_TiC, Rich_Web_VS_CP_TiO, Rich_Web_VS_CP_TiD, Rich_Web_VS_CP_TiP, Rich_Web_VS_CP_TiS, Rich_Web_VS_CP_TiBS, Rich_Web_VS_CP_TiBC, Rich_Web_VS_CP_TiBSt, Rich_Web_VS_CP_TiPos, Rich_Web_VS_SL_Width, Rich_Web_VS_SL_Height, Rich_Web_VS_TitDesc_Type) VALUES (%d, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", '', $Rich_Web_VS_ID[0]->id, 'Content Slider', 'Content Slider', 'random', 'swing', '10', '20', '16', '800', '8', '10', 'on', 'on', 'on', '#666666', '0', 'solid', '#ffffff', '1', 'on', 'on', '50', 'on', '1', '1', '500', 'swing', '50', 'expanddown', '18', 'Aldhabi', '#000000', '#ffffff', '18', 'Aldhabi', 'rgba(221,51,51,0.9)', '#ffffff', '360bar', '#ffffff', '#000000', '50', '16', '5', '6', '6', '#dd3333', 'solid', 'top-left', '700', '400', 'type1'));
}
$Rich_Web_VS1_Loader=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name5_Loader WHERE id>%d",0));
if(count($Rich_Web_VS1_Loader) == 0)
{
	$Rich_Web_VS_ID=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name4 WHERE slider_vid_name=%s", 'Content Slider'));
	$wpdb->query($wpdb->prepare("INSERT INTO $table_name5_Loader (id, RW_VS_ID, Rich_Web_VS_ContSl_L_Show, Rich_Web_VS_ContSl_LT_Show, Rich_Web_VS_ContSl_LT, Rich_Web_VS_ContSl_L_BgC, Rich_Web_VS_ContSl_L_T, Rich_Web_VS_ContSl_LT_T, Rich_Web_VS_ContSl_LT_FS, Rich_Web_VS_ContSl_LT_FF, Rich_Web_VS_ContSl_LT_C, Rich_Web_VS_ContSl_L_T1_C, Rich_Web_VS_ContSl_L_T2_C, Rich_Web_VS_ContSl_L_T3_C, Rich_Web_VS_ContSl_LT_T2_BC, Rich_Web_VS_ContSl_L_C, Rich_Web_VS_ContSl_LT_T2_AnC, Rich_Web_VS_ContSl_LT_T3_BgC, Rich_Web_VS_ContSl_L_S, Rich_Web_VS_ContSl_Loading_Show) VALUES (%d, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", '', $Rich_Web_VS_ID[0]->id, 'on', 'on', 'Loading', 'rgba(255,255,255,0)', 'Type 3', 'Type 2', '13', 'Abadi MT Condensed Light', '#dd0000', '#dd9933', '#dd9933', '#dd3333', 'rgba(30,115,190,0.54)', '#dd3333', '#dd3333', '#dd3333', 'middle', 'on'));
}
$Rich_Web_VS3=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name7 WHERE id>%d",0));
if(count($Rich_Web_VS3)==0)
{
	$wpdb->query($wpdb->prepare("INSERT INTO $table_name4 (id, slider_vid_name, slider_Vid_type) VALUES (%d, %s, %s)", '', 'Thumbnails Slider', 'Thumbnails Slider'));
	$Rich_Web_VS_ID=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name4 WHERE slider_vid_name=%s", 'Thumbnails Slider'));
	$wpdb->query($wpdb->prepare("INSERT INTO $table_name7 (id, RW_VS_ID, Rich_Web_VSlider_Option_Name, Rich_Web_VSlider_Option_Type, Rich_Web_VS_TS_W, Rich_Web_VS_TS_H, Rich_Web_VS_TS_BW, Rich_Web_VS_TS_BS, Rich_Web_VS_TS_BC, Rich_Web_VS_TS_BoxShShow, Rich_Web_VS_TS_BoxShType, Rich_Web_VS_TS_BoxSh, Rich_Web_VS_TS_BoxShC, Rich_Web_VS_TS_IBgC, Rich_Web_VS_TS_IBW, Rich_Web_VS_TS_IBS, Rich_Web_VS_TS_IBC, Rich_Web_VS_TS_IBR, Rich_Web_VS_TS_TPos, Rich_Web_VS_TS_TBgC, Rich_Web_VS_TS_TBW, Rich_Web_VS_TS_TBS, Rich_Web_VS_TS_TBC, Rich_Web_VS_TS_TIH, Rich_Web_VS_TS_TIPB, Rich_Web_VS_TS_TIBW, Rich_Web_VS_TS_TIBS, Rich_Web_VS_TS_TIBC, Rich_Web_VS_TS_TIBR, Rich_Web_VS_TS_TIBoxShShow, Rich_Web_VS_TS_TIBoxShType, Rich_Web_VS_TS_TIBoxSh, Rich_Web_VS_TS_TIBoxShC, Rich_Web_VS_TS_TICBC, Rich_Web_VS_TS_TICBS, Rich_Web_VS_TS_TICBoxShC, Rich_Web_VS_TS_TIHBC, Rich_Web_VS_TS_TIHBS, Rich_Web_VS_TS_TIHBoxShC, Rich_Web_VS_TS_CS, Rich_Web_VS_TS_PT, Rich_Web_VS_TS_AP, Rich_Web_VS_TS_PIBgC, Rich_Web_VS_TS_PIC, Rich_Web_VS_TS_PIHBgC, Rich_Web_VS_TS_PIHC) VALUES (%d, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", '', $Rich_Web_VS_ID[0]->id, 'Thumbnails Slider', 'Thumbnails Slider', '700', '350', '2', 'solid', '#ffffff', 'on', 'on', '30', '#a3a3a3', 'rgba(255,255,255,0.7)', '2', 'solid', 'rgba(255,255,255,0.7)', '6', 'bottom', '#000000', '1', 'solid', '#ffffff', '60', '5', '1', 'solid', '#ffffff', '3', 'on', '', '10', '#ffffff', '#707070', 'solid', '#ffffff', '#ffffff', 'solid', '#ffffff', '400', '5', '', 'rgba(255,255,255,0.7)', '#dd3333', 'rgba(221,51,51,0.7)', '#ffffff'));
}
$Rich_Web_VS3_Loader=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name7_Loader WHERE id>%d",0));
if(count($Rich_Web_VS3_Loader) == 0)
{
	$Rich_Web_VS_ID=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name4 WHERE slider_vid_name=%s", 'Thumbnails Slider'));
	$wpdb->query($wpdb->prepare("INSERT INTO $table_name7_Loader (id, RW_VS_ID, Rich_Web_ThumbSl_L_Show, Rich_Web_ThumbSl_LT_Show, Rich_Web_ThumbSl_LT, Rich_Web_ThumbSl_L_BgC, Rich_Web_ThumbSl_L_T, Rich_Web_ThumbSl_LT_T, Rich_Web_ThumbSl_LT_FS, Rich_Web_ThumbSl_LT_FF, Rich_Web_ThumbSl_LT_C, Rich_Web_ThumbSl_L_T1_C, Rich_Web_ThumbSl_L_T2_C, Rich_Web_ThumbSl_L_T3_C, Rich_Web_ThumbSl_LT_T2_BC, Rich_Web_ThumbSl_L_C, Rich_Web_ThumbSl_LT_T2_AnC, Rich_Web_ThumbSl_LT_T3_BgC, Rich_Web_ThumbSl_L_S, Rich_Web_ThumbSl_Loading_Show) VALUES (%d, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", '', $Rich_Web_VS_ID[0]->id, 'on', 'on', 'Loading', 'rgba(255,255,255,0.03)', 'Type 2', 'Type 4', '13', 'Abadi MT Condensed Light', '#841e1e', '#dd9933', '#dd9933', '#dd3333', 'rgba(30,115,190,0.54)', '#841e1e', '#ffffff', '#dd3333', 'small', 'on'));
}
$Rich_Web_VS4=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name8 WHERE id>%d",0));
if(count($Rich_Web_VS4)==0)
{
	$wpdb->query($wpdb->prepare("INSERT INTO $table_name4 (id, slider_vid_name, slider_Vid_type) VALUES (%d, %s, %s)", '', 'Video Carousel/Content Popup', 'Video Carousel/Content Popup'));
	$Rich_Web_VS_ID=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name4 WHERE slider_vid_name=%s", 'Video Carousel/Content Popup'));
	$wpdb->query($wpdb->prepare("INSERT INTO $table_name8 (id, RW_VS_ID, Rich_Web_VSlider_Option_Name, Rich_Web_VSlider_Option_Type, Rich_Web_VC_Car_Bg_Color, Rich_Web_VC_Car_Border_Width, Rich_Web_VC_Car_Border_Style, Rich_Web_VC_Car_Border_Color, Rich_Web_VC_Car_Box_Shadow, Rich_Web_VC_Car_Shadow_Color, Rich_Web_VC_Car_Count_Imgs, Rich_Web_VC_Car_Imgs_Hover_Type, Rich_Web_VC_Car_PBImgs, Rich_Web_VC_Car_Icons_Type, Rich_Web_VC_Car_Icons_Size, Rich_Web_VC_Overlay_Bg_Color, Rich_Web_VC_Popup_Bg_Color, Rich_Web_VC_Popup_Border_Width, Rich_Web_VC_Popup_Border_Style, Rich_Web_VC_Popup_Border_Color, Rich_Web_VC_Popup_Box_Shadow, Rich_Web_VC_Popup_Shadow_Color, Rich_Web_VC_Title_Font_Size, Rich_Web_VC_Title_Font_Family, Rich_Web_VC_Title_Color, Rich_Web_VC_Title_Text_Align, Rich_Web_VC_Desc_Bg_Color, Rich_Web_VC_Desc_Font_Size, Rich_Web_VC_Desc_Font_Family, Rich_Web_VC_Desc_Color, Rich_Web_VC_Desc_Text_Align, Rich_Web_VC_Link_Font_Size, Rich_Web_VC_Link_Font_Family, Rich_Web_VC_Link_Color, Rich_Web_VC_Link_Bg_Color, Rich_Web_VC_Link_Border_Color, Rich_Web_VC_Link_Border_Width, Rich_Web_VC_Link_Border_Style, Rich_Web_VC_Link_Hov_Bg_Color, Rich_Web_VC_Link_Hov_Color, Rich_Web_VC_Link_Hov_Border_Color, Rich_Web_VC_Popup_Icons_Size, Rich_Web_VC_Popup_Icons_Color, Rich_Web_VC_Popup_Icons_Type, Rich_Web_VC_Link_Text, Rich_Web_VC_Link_Border_Radius) VALUES (%d, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", '', $Rich_Web_VS_ID[0]->id, 'Video Carousel/Content Popup', 'Video Carousel/Content Popup', '#ffffff', '0', 'solid', '#ffffff', '25', '#009491', '4', 'fImgH1', '5', '10', '25', 'rgba(255,255,255,0)', 'rgba(0,0,0,0.7)', '0', 'solid', '#ffffff', '25', '#000000', '24', 'Vijaya', '#ffffff', 'center', 'rgba(0,148,145,0)', '16', 'Aldhabi', '#ffffff', 'left', '15', 'Vijaya', '#000000', 'rgba(255,255,255,0.8)', '#ffffff', '1', 'solid', 'rgba(0,0,0,0.8)', '#ffffff', '#000000', '25', '#ffffff', 'rich_web-times-circle', 'View More', '0'));
}
$Rich_Web_VS4_Loader=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name8_Loader WHERE id>%d",0));
if(count($Rich_Web_VS4_Loader) == 0)
{
	$Rich_Web_VS_ID=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name4 WHERE slider_vid_name=%s", 'Video Carousel/Content Popup'));
	$wpdb->query($wpdb->prepare("INSERT INTO $table_name8_Loader (id, RW_VS_ID, Rich_Web_VCCP_L_Show, Rich_Web_VCCP_LT_Show, Rich_Web_VCCP_LT, Rich_Web_VCCP_L_BgC, Rich_Web_VCCP_L_T, Rich_Web_VCCP_LT_T, Rich_Web_VCCP_LT_FS, Rich_Web_VCCP_LT_FF, Rich_Web_VCCP_LT_C, Rich_Web_VCCP_L_T1_C, Rich_Web_VCCP_L_T2_C, Rich_Web_VCCP_L_T3_C, Rich_Web_VCCP_LT_T2_BC, Rich_Web_VCCP_L_C, Rich_Web_VCCP_LT_T2_AnC, Rich_Web_VCCP_LT_T3_BgC, Rich_Web_VCCP_L_S, Rich_Web_VCCP_Loading_Show) VALUES (%d, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", '', $Rich_Web_VS_ID[0]->id, '', 'on', 'Loading', '#ffffff', 'Type 2', 'Type 1', '15', 'Arial Black', '#540a1c', '#dd9933', '#dd9933', '#dd3333', 'rgba(0,0,0,0.3)', '#0084aa', '#ffffff', '#dd3333', 'small', 'on'));
}
$Rich_Web_VS6=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name10 WHERE id>%d",0));
if(count($Rich_Web_VS6)==0)
{
	$wpdb->query($wpdb->prepare("INSERT INTO $table_name4 (id, slider_vid_name, slider_Vid_type) VALUES (%d, %s, %s)", '', 'Video Slider/Vertical Thumbnails', 'Video Slider/Vertical Thumbnails'));
	$Rich_Web_VS_ID=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name4 WHERE slider_vid_name=%s", 'Video Slider/Vertical Thumbnails'));
	$wpdb->query($wpdb->prepare("INSERT INTO $table_name10 (id, RW_VS_ID, Rich_Web_VSlider_Option_Name, Rich_Web_VSlider_Option_Type, Rich_Web_VTVS_AP, Rich_Web_VTVS_APS, Rich_Web_VTVS_APEff, Rich_Web_VTVS_CS, Rich_Web_VTVS_PT, Rich_Web_VTVS_ArrSt, Rich_Web_VTVS_BgC, Rich_Web_VTVS_H, Rich_Web_VTVS_BW, Rich_Web_VTVS_BS, Rich_Web_VTVS_BC, Rich_Web_VTVS_BoxShShow, Rich_Web_VTVS_BoxShType, Rich_Web_VTVS_BoxSh, Rich_Web_VTVS_BoxShC, Rich_Web_VTVS_TShow, Rich_Web_VTVS_TFS, Rich_Web_VTVS_TFF, Rich_Web_VTVS_TC, Rich_Web_VTVS_TBgC, Rich_Web_VTVS_TPos, Rich_Web_VTVS_Th_BW, Rich_Web_VTVS_Th_BS, Rich_Web_VTVS_Th_BC, Rich_Web_VTVS_Th_BR, Rich_Web_VTVS_Th_HBC, Rich_Web_VTVS_LC, Rich_Web_VTVS_LBgC, Rich_Web_VTVS_LFS, Rich_Web_VTVS_LHC, Rich_Web_VTVS_LHBgC, Rich_Web_VTVS_LPos, Rich_Web_VTVS_LType, Rich_Web_VTVS_PC, Rich_Web_VTVS_PBgC, Rich_Web_VTVS_PFS, Rich_Web_VTVS_PHC, Rich_Web_VTVS_PHBgC, Rich_Web_VTVS_PPos, Rich_Web_VTVS_PType, Rich_Web_VTVS_ArrShow, Rich_Web_VTVS_ArrType, Rich_Web_VTVS_ArrFS, Rich_Web_VTVS_ArrPos, Rich_Web_VTVS_ArrC) VALUES (%d, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", '', $Rich_Web_VS_ID[0]->id, 'Video Slider/Vertical Thumbnails', 'Video Slider/Vertical Thumbnails', 'on', '1', 'fade slideshow', '700', '2', '1', '#000000', '350', '0', 'solid', '#ffffff', 'on', 'on', '50', '#6b6b6b', 'on', '22', 'Aldhabi', '#ffffff', 'rgba(0,0,0,0.6)', 'top', '2', 'solid', '#ffffff', '0', '#545454', '#000000', 'rgba(255,255,255,0.7)', '23', '#ffffff', 'rgba(0,0,0,0.7)', 'bottom-right', 'link', 'rgba(0,0,0,0.7)', 'rgba(255,255,255,0.7)', '23', '#ffffff', 'rgba(0,0,0,0.7)', 'bottom-left', 'play-circle', 'on', 'chevron-circle', '25', 'center', '#ffffff'));
}
$Rich_Web_VS6_Loader=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name10_Loader WHERE id>%d",0));
if(count($Rich_Web_VS6_Loader) == 0)
{
	$Rich_Web_VS_ID=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name4 WHERE slider_vid_name=%s", 'Video Slider/Vertical Thumbnails'));
	$wpdb->query($wpdb->prepare("INSERT INTO $table_name10_Loader (id, RW_VS_ID, Rich_Web_VSVT_L_Show, Rich_Web_VSVT_LT_Show, Rich_Web_VSVT_LT, Rich_Web_VSVT_L_BgC, Rich_Web_VSVT_L_T, Rich_Web_VSVT_LT_T, Rich_Web_VSVT_LT_FS, Rich_Web_VSVT_LT_FF, Rich_Web_VSVT_LT_C, Rich_Web_VSVT_L_T1_C, Rich_Web_VSVT_L_T2_C, Rich_Web_VSVT_L_T3_C, Rich_Web_VSVT_LT_T2_BC, Rich_Web_VSVT_L_C, Rich_Web_VSVT_LT_T2_AnC, Rich_Web_VSVT_LT_T3_BgC, Rich_Web_VSVT_L_S, Rich_Web_VSVT_Loading_Show) VALUES (%d, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", '', $Rich_Web_VS_ID[0]->id, 'on', 'on', 'Loading', '#ffffff', 'Type 4', 'Type 4', '13', 'Abadi MT Condensed Light', '#59d600', '#dd9933', '#dd9933', '#dd3333', 'rgba(30,115,190,0.54)', '#59d600', '#ffffff', '#dd3333', 'small', 'on'));
}
$Rich_Web_VS7=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name11 WHERE id>%d",0));
if(count($Rich_Web_VS7)==0)
{
	$wpdb->query($wpdb->prepare("INSERT INTO $table_name4 (id, slider_vid_name, slider_Vid_type) VALUES (%d, %s, %s)", '', 'Horizontal Posts Slider', 'Horizontal Posts Slider'));
	$Rich_Web_VS_ID=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name4 WHERE slider_vid_name=%s", 'Horizontal Posts Slider'));
	$wpdb->query($wpdb->prepare("INSERT INTO $table_name11 (id, RW_VS_ID, Rich_Web_VSlider_Option_Name, Rich_Web_VSlider_Option_Type, Rich_Web_VS_HPS_Loop, Rich_Web_VS_HPS_Cols, Rich_Web_VS_HPS_Speed, Rich_Web_VS_HPS_AP, Rich_Web_VS_HPS_EH, Rich_Web_VS_HPS_PB, Rich_Web_VS_HPS_Car, Rich_Web_VS_HPS_NP_Show, Rich_Web_VS_HPS_NP_NText, Rich_Web_VS_HPS_NP_PText, Rich_Web_VS_HPS_NP_C, Rich_Web_VS_HPS_NP_BgC, Rich_Web_VS_HPS_NP_FS, Rich_Web_VS_HPS_NP_FF, Rich_Web_VS_HPS_NP_BW, Rich_Web_VS_HPS_NP_BS, Rich_Web_VS_HPS_NP_BC, Rich_Web_VS_HPS_NP_BR, Rich_Web_VS_HPS_NP_HC, Rich_Web_VS_HPS_NP_HBgC, Rich_Web_VS_HPS_Cols_BgC, Rich_Web_VS_HPS_Cols_BoxShC, Rich_Web_VS_HPS_Cols_VSEff, Rich_Web_VS_HPS_Cols_StShC, Rich_Web_VS_HPS_Cols_VHEff, Rich_Web_VS_HPS_Cols_HShC, Rich_Web_VS_HPS_TC, Rich_Web_VS_HPS_TFS, Rich_Web_VS_HPS_TFF, Rich_Web_VS_HPS_DShow, Rich_Web_VS_HPS_DC, Rich_Web_VS_HPS_DFS, Rich_Web_VS_HPS_DFF, Rich_Web_VS_HPS_LText, Rich_Web_VS_HPS_LC, Rich_Web_VS_HPS_LFS, Rich_Web_VS_HPS_LFF, Rich_Web_VS_HPS_LHC, Rich_Web_VS_HPS_PText, Rich_Web_VS_HPS_PBgC, Rich_Web_VS_HPS_PC, Rich_Web_VS_HPS_PFS, Rich_Web_VS_HPS_PFF, Rich_Web_VS_HPS_PHC, Rich_Web_VS_HPS_PHBgC, Rich_Web_VS_HPS_Pop_OvC, Rich_Web_VS_HPS_Pop_BW, Rich_Web_VS_HPS_Pop_BS, Rich_Web_VS_HPS_Pop_BC, Rich_Web_VS_HPS_Pop_BoxShShow, Rich_Web_VS_HPS_Pop_BoxShType, Rich_Web_VS_HPS_Pop_BoxSh, Rich_Web_VS_HPS_Pop_BoxShC, Rich_Web_VS_HPS_Pop_CIType, Rich_Web_VS_HPS_Pop_CIS, Rich_Web_VS_HPS_Pop_CIC) VALUES (%d, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", '', $Rich_Web_VS_ID[0]->id, 'Horizontal Posts Slider', 'Horizontal Posts Slider', 'on', '3', '3', '', 'on', '20', 'on', 'on', 'Next', 'Prev', '#6d6d6d', '#ffffff', '20', 'Gabriola', '1', 'solid', '#6d6d6d', '3', '#000000', '#ffffff', '#ffffff', '#6d6d6d', 'none', '#ffffff', 'drop-shadow', '#9e9e9e', '#000000', '24', 'Vijaya', 'on', '#6d6d6d', '14', 'Aldhabi', 'View More ...', '#000000', '18', 'Vijaya', '#6d6d6d', 'Watch Video ...', '#000000', '#ffffff', '13', 'Arial', '#ffffff', '#383838', 'rgba(0,0,0,0.5)', 'none', 'solid', 'rgba(0,144,170,0.5)', 'on', 'on', '19', 'rgba(0,0,0,0.59)', 'rich_web-times', '35', 'rgba(255,255,255,0.8)'));
}
$Rich_Web_VS7_Loader=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name11_Loader WHERE id>%d",0));
if(count($Rich_Web_VS7_Loader) == 0)
{
	$Rich_Web_VS_ID=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name4 WHERE slider_vid_name=%s", 'Horizontal Posts Slider'));
	$wpdb->query($wpdb->prepare("INSERT INTO $table_name11_Loader (id, RW_VS_ID, Rich_Web_HSL_L_Show, Rich_Web_HSL_LT_Show, Rich_Web_HSL_LT, Rich_Web_HSL_L_BgC, Rich_Web_HSL_L_T, Rich_Web_HSL_LT_T, Rich_Web_HSL_LT_FS, Rich_Web_HSL_LT_FF, Rich_Web_HSL_LT_C, Rich_Web_HSL_L_T1_C, Rich_Web_HSL_L_T2_C, Rich_Web_HSL_L_T3_C, Rich_Web_HSL_LT_T2_BC, Rich_Web_HSL_L_C, Rich_Web_HSL_LT_T2_AnC, Rich_Web_HSL_LT_T3_BgC, Rich_Web_HSL_L_S, Rich_Web_HSL_Loading_Show) VALUES (%d, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", '', $Rich_Web_VS_ID[0]->id, 'on', 'on', 'Loading', '#ffffff', 'Type 4', 'Type 4', '23', 'Calibri', '#000000', '#dd9933', '#dd9933', '#dd3333', 'rgba(30,115,190,0.54)', '#b1ba09', '#ffffff', '#dd3333', 'small', 'on'));
}
$Rich_Web_VS8=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name12 WHERE id>%d",0));
if(count($Rich_Web_VS8)==0)
{
	$wpdb->query($wpdb->prepare("INSERT INTO $table_name4 (id, slider_vid_name, slider_Vid_type) VALUES (%d, %s, %s)", '', 'Rich Slider', 'Rich Slider'));
	$Rich_Web_VS_ID=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name4 WHERE slider_vid_name=%s", 'Rich Slider'));
	$wpdb->query($wpdb->prepare("INSERT INTO $table_name12 (id, RW_VS_ID, Rich_Web_VSlider_Option_Name, Rich_Web_VSlider_Option_Type, Rich_Web_RVVS_Sh, Rich_Web_RVVS_ShT, Rich_Web_RVVS_ShC, Rich_Web_RVVS_NI_BW, Rich_Web_RVVS_NI_BC, Rich_Web_RVVS_NI_BgC, Rich_Web_RVVS_NI_HBgC,Rich_Web_RVVS_NI_HBC, Rich_Web_RVVS_NI_CBgC, Rich_Web_RVVS_NI_CBC, Rich_Web_RVVS_NT_FF, Rich_Web_RVVS_NT_C, Rich_Web_RVVS_ND_FF, Rich_Web_RVVS_ND_C, Rich_Web_RVVS_NImg_BW, Rich_Web_RVVS_NImg_BR, Rich_Web_RVVS_NImg_BSh, Rich_Web_RVVS_NImg_ShC, Rich_Web_RVVS_NImg_ShT, Rich_Web_RVVS_NScroll_BgC, Rich_Web_RVVS_NScroll_HBgC, Rich_Web_RVVS_NScroll_C, Rich_Web_RVVS_IT_FF, Rich_Web_RVVS_IT_C, Rich_Web_RVVS_ID_FF, Rich_Web_RVVS_ID_C, Rich_Web_RVVS_PlIc_FS, Rich_Web_RVVS_PlIc_C, Rich_Web_RVVS_PlIc_BgC, Rich_Web_RVVS_PlIc_HBgC, Rich_Web_RVVS_DelIc_C, Rich_Web_RVVS_DelIc_T, Rich_Web_RVVS_DelIc_FS, Rich_Web_RVVS_DelIc_BgC, Rich_Web_RVVS_DelIc_HBgC, Rich_Web_RVVS_NT_FS, Rich_Web_RVVS_ND_FS, Rich_Web_RVVS_IT_FS, Rich_Web_RVVS_ID_FS, Rich_Web_RVVS_NT_HC, Rich_Web_RVVS_NT_CC, Rich_Web_RVVS_ND_HC, Rich_Web_RVVS_ND_CC) VALUES (%d, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", '', $Rich_Web_VS_ID[0]->id, 'Rich Slider', 'Rich Slider', '10', 'Type 1', '#000000', '0', '#bcbcbc', '#ffffff', '#bcbcbc', '#ffffff', '#bcbcbc', '#ffffff', 'Abadi MT Condensed Light', '#000000', 'Abadi MT Condensed Light', '#686868', '0', '0', '8', '#000000', 'Type 1', 'rgba(0,0,0,0.6)', '#ffffff', '#ffffff', 'Aldhabi', '#ffffff', 'Abadi MT Condensed Light', '#dd9933', '29', '#ffffff', 'rgba(0,0,0,0.5)', 'rgba(0,0,0,0.7)', '#ffffff', 'rich_web-times', '25', 'rgba(0,0,0,0.5)', 'rgba(0,0,0,0.7)', '15', '13', '20', '16','#ffffff','#ffffff','#eaeaea','#eaeaea'));
}
$Rich_Web_VS8_Loader=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name12_Loader WHERE id>%d",0));
if(count($Rich_Web_VS8_Loader) == 0)
{
	$Rich_Web_VS_ID=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name4 WHERE slider_vid_name=%s", 'Rich Slider'));
	$wpdb->query($wpdb->prepare("INSERT INTO $table_name12_Loader (id, RW_VS_ID, Rich_Web_RichSl_L_Show, Rich_Web_RichSl_LT_Show, Rich_Web_RichSl_LT, Rich_Web_RichSl_L_BgC, Rich_Web_RichSl_L_T, Rich_Web_RichSl_LT_T, Rich_Web_RichSl_LT_FS, Rich_Web_RichSl_LT_FF, Rich_Web_RichSl_LT_C, Rich_Web_RichSl_L_T1_C, Rich_Web_RichSl_L_T2_C, Rich_Web_RichSl_L_T3_C, Rich_Web_RichSl_LT_T2_BC, Rich_Web_RichSl_L_C, Rich_Web_RichSl_LT_T2_AnC, Rich_Web_RichSl_LT_T3_BgC, Rich_Web_RichSl_L_S, Rich_Web_RichSl_Loading_Show) VALUES (%d, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", '', $Rich_Web_VS_ID[0]->id, '', 'on', 'Loading', 'rgba(255,255,255,0.09)', 'Type 4', 'Type 3', '13', 'Abadi MT Condensed Light', '#ffffff', '#dd9933', '#dd9933', '#dd3333', 'rgba(30,115,190,0.54)', '#0084aa', '#ffffff', '#dd3333', 'small', 'on'));
}
$Rich_Web_VS9=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name13 WHERE id>%d",0));
if(count($Rich_Web_VS9)==0)
{
	$wpdb->query($wpdb->prepare("INSERT INTO $table_name4 (id, slider_vid_name, slider_Vid_type) VALUES (%d, %s, %s)", '', 'Timeline', 'TimeLine Slider'));
	$Rich_Web_VS_ID=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name4 WHERE slider_vid_name=%s", 'Timeline'));
	$wpdb->query($wpdb->prepare("INSERT INTO $table_name13 (id, RW_VS_ID, Rich_Web_VSlider_Option_Name, Rich_Web_VSlider_Option_Type, Rich_Web_MS_W, Rich_Web_MS_SSh, Rich_Web_MS_SShChT, Rich_Web_MS_BSh, Rich_Web_MS_ShC, Rich_Web_MS_ShT, Rich_Web_MS_BgC, Rich_Web_MS_Type, Rich_Web_MS_Autoplay, Rich_Web_MS_N_BW, Rich_Web_MS_N_BS, Rich_Web_MS_N_BC, Rich_Web_MS_NI_FS, Rich_Web_MS_NI_FF, Rich_Web_MS_NI_C, Rich_Web_MS_NI_HC, Rich_Web_MS_NI_CC, Rich_Web_MS_NIC_C, Rich_Web_MS_Img_BW, Rich_Web_MS_Img_BS, Rich_Web_MS_Img_BC, Rich_Web_MS_Img_BSh, Rich_Web_MS_Img_ShC, Rich_Web_MS_Img_ShT, Rich_Web_MS_T_FS, Rich_Web_MS_T_FF, Rich_Web_MS_T_C, Rich_Web_MS_T_TA, Rich_Web_MS_T_TSh, Rich_Web_MS_T_TShC, Rich_Web_MS_D_FS, Rich_Web_MS_D_FF, Rich_Web_MS_D_C, Rich_Web_MS_D_TA, Rich_Web_MS_D_TSh, Rich_Web_MS_D_TShC, Rich_Web_MS_Ic_T, Rich_Web_MS_Ic_S, Rich_Web_MS_Ic_C, Rich_Web_MS_startAt, Rich_Web_MS_Sl1EfT, Rich_Web_MS_NI_CCC, Rich_Web_MS_PlIc_T, Rich_Web_MS_PlIc_S, Rich_Web_MS_PlIc_BgC, Rich_Web_MS_PlIc_C, Rich_Web_MS_PlIc_HBgC, Rich_Web_MS_PlIc_HC) VALUES (%d, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", '', $Rich_Web_VS_ID[0]->id, "Timeline", "TimeLine Slider", "800", "", "1694", "10", "#000000", "Type 1", "rgba(255,255,255,0.51)", "horizontal", "", "1", "solid", "#dbdbdb", "13", "Abadi MT Condensed Light", "#1e73be", "#0066bf", "#144e91", "#000000", "3", "solid", "#ffffff", "10", "#919191", "Type 2", "16", "Abadi MT Condensed Light", "#1e73be", "center", "1", "#afafaf", "14", "Abadi MT Condensed Light", "#595959", "justify", "0", "#000000", "rich_web rich_web-long-arrow", "20", "#1e73be", "1", "2", "", "rich_web rich_web-play-circle", "28", "rgba(221,0,0,0.45)", "#ffffff", "rgba(221,51,51,0.45)", "#ffffff"));
}
$Rich_Web_VS9_Loader=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name13_Loader WHERE id>%d",0));
if(count($Rich_Web_VS9_Loader) == 0)
{
	$Rich_Web_VS_ID=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name4 WHERE slider_vid_name=%s", 'Timeline'));
	$wpdb->query($wpdb->prepare("INSERT INTO $table_name13_Loader (id, RW_VS_ID, Rich_Web_TSL_L_Show, Rich_Web_TSL_LT_Show, Rich_Web_TSL_LT, Rich_Web_TSL_L_BgC, Rich_Web_TSL_L_T, Rich_Web_TSL_LT_T, Rich_Web_TSL_LT_FS, Rich_Web_TSL_LT_FF, Rich_Web_TSL_LT_C, Rich_Web_TSL_L_T1_C, Rich_Web_TSL_L_T2_C, Rich_Web_TSL_L_T3_C, Rich_Web_TSL_LT_T2_BC, Rich_Web_TSL_L_C, Rich_Web_TSL_LT_T2_AnC, Rich_Web_TSL_LT_T3_BgC, Rich_Web_TSL_L_S, Rich_Web_TSL_Loading_Show) VALUES (%d, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", '', $Rich_Web_VS_ID[0]->id, 'on', 'on', 'Loading', '#ffffff', 'Type 4', 'Type 4', '13', 'Abadi MT Condensed Light', '#dd3333', '#dd9933', '#dd9933', '#dd3333', 'rgba(30,115,190,0.54)', '#0084aa', '#ffffff', '#dd3333', 'small', 'on'));
}
$RichWeb_VidSl_ID = '';
$RW_VidSl_DigitCheck = $wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name2 WHERE id>%d",0));
if (is_numeric($RW_VidSl_DigitCheck[0]->Slider_Type) != TRUE) {
	for ($i=0; $i < count($RW_VidSl_DigitCheck); $i++) {
		$RichWeb_VidSl_ID = $wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name4 WHERE slider_vid_name=%s order by id asc limit 1", $RW_VidSl_DigitCheck[$i]->Slider_Type));
		$wpdb->query($wpdb->prepare("UPDATE $table_name2 set Slider_Type=%s WHERE id=%s", $RichWeb_VidSl_ID[0]->id, $RW_VidSl_DigitCheck[$i]->id));
	}
}
$RW_VS_All_Ins = $Rich_Web_VS_Upd = $RW_Files_Arr = [];
$Rich_Web_VS_Options=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name4 WHERE id>%d",0));
foreach($Rich_Web_VS_Options as $RW_VS_Opt_Types) { $RW_VS_All_Ins[] = $RW_VS_Opt_Types->slider_Vid_type; }
$RW_VS_All_Ins = array_values(array_unique($RW_VS_All_Ins));
if (!in_array('Amazing Simple Slider',$RW_VS_All_Ins)) {
	$RW_Files_Arr[] = plugin_dir_path( __FILE__ ) . 'PHP/RW_VS_Slider_Amazing.php';
	$RW_Files_Arr[] = plugin_dir_path( __FILE__ ) . 'Style/RW_VS_Slider_Amazing.css.php';
	$RW_Files_Arr[] = plugin_dir_path( __FILE__ ) . 'Scripts/RW_VS_Slider_Amazing.js.php';
}
if (!in_array('Slick Slider',$RW_VS_All_Ins) ) {
	$RW_Files_Arr[] = plugin_dir_path( __FILE__ ) . 'PHP/RW_VS_Slider_Slick.php';
	$RW_Files_Arr[] = plugin_dir_path( __FILE__ ) . 'Style/RW_VS_Slider_Slick.css.php';
	$RW_Files_Arr[] = plugin_dir_path( __FILE__ ) . 'Scripts/RW_VS_Slider_Slick.js.php';
}
if (!in_array('Simple Video Slider',$RW_VS_All_Ins)) {
	$RW_Files_Arr[] = plugin_dir_path( __FILE__ ) . 'PHP/RW_VS_Slider_Simple.php';
	$RW_Files_Arr[] = plugin_dir_path( __FILE__ ) . 'Style/RW_VS_Slider_Simple.css.php';
	$RW_Files_Arr[] = plugin_dir_path( __FILE__ ) . 'Scripts/RW_VS_Slider_Simple.js.php';
}
if (count($RW_Files_Arr) != 0) {
	foreach ($RW_Files_Arr as $key => $value) {
		if (file_exists($value) == TRUE) { unlink($value); }
	}
}
?>